# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Opacus Python Package to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        rm -rf dist/
        python setup.py sdist bdist_wheel
        twine upload dist/*

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa # v2.1.3
      with:
        workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}
        token_format: access_token
        access_token_lifetime: 3600s

    - name: Publish Python package to GCLOUD
      shell: bash
      env:
        TWINE_USERNAME: "oauth2accesstoken"
        TWINE_PASSWORD: ${{ steps.auth.outputs.access_token }}
        TWINE_REPOSITORY_URL: ${{vars.GCLOUD_PYTHON_REGISTRY}}
      run: |   
        twine upload dist/*
